name: codersfree-inertia
recipe: laravel
config:
  webroot: public
  php: '8.1'
  via: nginx
services:
  database:
    type: mariadb
    creds:
      database: codersfree
  appserver:
    xdebug: true
    config:
      php: .lando/php.ini
  phpAdmin:
    type: phpmyadmin
  node:
    type: node
    command: npm start
  cache:
    type: redis
tooling:
  npm:
    service: node